In [1]:
import numpy as np

# Câu 1

In [2]:
list = [1,2,3,4,5]
array = np.array(list)

print("Mảng Numpy:", array)

Mảng Numpy: [1 2 3 4 5]


# Câu 2

In [5]:
ma_tran_3x3 = np.arange(9).reshape(3,3)

print("Ma trận 3x3:\n",
      ma_tran_3x3)

Ma trận 3x3:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


# Câu 4

In [6]:
max = np.max(list)
min = np.min(list)

print("Giá trị lớn nhất:",max)
print("Giá trị nhỏ nhất:", min)

Giá trị lớn nhất: 5
Giá trị nhỏ nhất: 1


# Câu 5

In [9]:
random = np.random.rand(3,3)

print("Mảng 2D với giá trị ngẫu nhiên:")
print(random)

Mảng 2D với giá trị ngẫu nhiên:
[[0.37920159 0.44888072 0.91985645]
 [0.75648781 0.90826534 0.26982452]
 [0.9252279  0.9756379  0.73843177]]


# Câu 6

In [12]:
trung_binh = np.mean(list)
print("Giá trị trung bình cộng:", trung_binh)

Giá trị trung bình cộng: 3.0


# Câu 7

In [16]:
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8,9],[10,11,12],[13,14,15]])
product = np.dot(A,B)
print ("TÍch của hai ma trận A và B:")
print(product)

TÍch của hai ma trận A và B:
[[ 66  72  78]
 [156 171 186]]


# Câu 8

In [23]:
mang = np.array([1,3,4,1,13,54,66,76,104,80,4,80,12])
mang_chan = mang[mang % 2 == 0]

print("Các phần tử chẵn trong mảng:", np.unique(mang_chan))

Các phần tử chẵn trong mảng: [  4  12  54  66  76  80 104]


# Câu 9

In [24]:
sap_xep = np.sort(mang)

print("Mảng đã sắp xếp theo thứ tự tăng dần:", sap_xep)

Mảng đã sắp xếp theo thứ tự tăng dần: [  1   1   3   4   4  12  13  54  66  76  80  80 104]


# Câu 10

In [25]:
ma_tran_2x2 = np.array([[1,2],[3,4]])

dinh_thuc = np.linalg.det(ma_tran_2x2)

print("Định thức của ma trận 2x2:",dinh_thuc)

Định thức của ma trận 2x2: -2.0000000000000004
